# Put this file in the same directory as the server.
port = 49153  # Port to host on. Standard is 49153. Only matters outside of a docker installation.
server_name = "Messenger Server"  # Name of this server to be shown to clients

[structure]
    data_folder= "./persistent"  # Path to the directory to put our data in. If one doesn't exist, it will created.
    log_file = "server.log"
    db = "messenger.db"  # Name of the database file to use. If it doesn't exist, one will be created.

# Session settings.
[session]
    [session.server_user]
        name = "server"  # The account used by the server for announcements.
        password = "admin"  # Not a security threat as you cannot login twice as the server.
        # If a user with these credentials does not exist, one will be created automatically.

    # Database currently is SQLite3.
    [session.database]
        allow_user_creation = true  # Allows anonymous connections to create accounts.
        max_shown_messages = 100  # Max amount of messages in the catalog to be sent to a client.
        message_character_limit = 200  # The maximum length of a message that can be posted by a client.
        username_character_limit = 20  # Maximum length of a username that can be used by a client.
    
    # Server announces certain events using these string. 
    # {user} gets replaced with the name of the user in question.
    [session.announcements]
        leave = "{user} has left."  # For when a user logs out.
        join = "{user} has joined."  # For when an anonymous connection logs itself in.
        abrupt_leave = "{user} left unexpectedly."  # When a user leaves without logging out first.
        # It MIGHT mean that it was abrupt; or just that they forgot to log out before leaving.
